# permissions for end users to view bookservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bookserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-crd
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: bookserver-viewer-role
rules:
- apiGroups:
  - bookcrd.github.com
  resources:
  - bookservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bookcrd.github.com
  resources:
  - bookservers/status
  verbs:
  - get
