---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bookcrd.github.com
  resources:
  - bookservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookcrd.github.com
  resources:
  - bookservers/finalizers
  verbs:
  - update
- apiGroups:
  - bookcrd.github.com
  resources:
  - bookservers/status
  verbs:
  - get
  - patch
  - update
