---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.github.com
  resources:
  - mobaraks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.github.com
  resources:
  - mobaraks/finalizers
  verbs:
  - update
- apiGroups:
  - crd.github.com
  resources:
  - mobaraks/status
  verbs:
  - get
  - patch
  - update
