apiVersion: bookcrd.github.com/v1
kind: BookServer
metadata:
  labels:
    app.kubernetes.io/name: bookserver
    app.kubernetes.io/instance: bookserver-sample
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-crd
  name: bookserver-sample
  namespace: kubebuilder-test
spec:
  replicas: 1
  container:
    image: "mobarak9239/api-server:latest"
    port: 8081
  service:
    serviceType: "NodePort"
    servicePort: 8081
#    serviceNodePort: 30001
