apiVersion: crd.github.com/v1
kind: BookServer
metadata:
  labels:
    app.kubernetes.io/name: mobarak
    app.kubernetes.io/instance: mobarak-sample
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-crd
  name: bookserver-sample
  namespace: kubebuilder-test
spec:
  replicas: 2
  container:
    image: "mobarak9239/api-server:latest"
    port: 8081
  service:
    serviceName: "api-server"
    serviceType: "NodePort"
    servicePort: 8081
#    serviceNodePort: 30001