apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookserver-controller
  namespace: kubebuilder-test
spec:
  selector:
    matchLabels:
      app: bookserver-controller
  template:
    metadata:
      labels:
        app: bookserver-controller
    spec:
      containers:
        - name: bookserver-controller
          image: mobarak9239/kubebuilder-crd:1.1.2
          ports:
            - containerPort: 8083