apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubebuilder-test
roleRef:
  kind: ClusterRole
  name: manager-role
  apiGroup: rbac.authorization.k8s.io